# Generated by Django 5.2.6 on 2025-09-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='user_avatar/default_avatar.png', null=True, upload_to='user_avatar'),
        ),
    ]
